version: '3'
services:
  eureka-service:
    container_name: eureka-service
    build: eureka-service
    image: eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - forum-network
    restart: on-failure:5
  gateway-service:
    container_name: gateway-service
    build: gateway-service
    image: gateway-service:latest
    ports:
      - "8080:8080"
    networks:
      - forum-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-service
    restart: on-failure:5
  db:
    container_name: user-db
    image: mariadb:latest
    ports: 
      - 3007:3306
    networks:
      - forum-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./member-service/db/schema:/home/mysql/schema
      - ./member-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=1234 --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5
  member-service:
    container_name: member-service
    build: member-service
    image: member-service:latest
    networks:
      - forum-network
    #ports:
      #- "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
      - eureka-service
    restart: on-failure:5
networks:
  forum-network:
  #for member service backend