version: '3'
services:
  db:
    container_name: user-db
    image: mariadb:latest
    ports: 
      - 3007:3306
    networks:
      - member-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db/schema:/home/mysql/schema
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=1234 --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5
  app:
    container_name: member-service
    build: .
    networks:
      - member-network
    ports:
      - "8080:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    restart: on-failure:5
networks:
  member-network:
  #for member service backend